import Link from "next/link";
import Head from "next/head";
import { useContext, useState, useEffect } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Store } from "../utils/Store";
import { signOut, useSession } from "next-auth/react";
import { Menu } from "@headlessui/react";
import DropdownLink from "./DropdownLink";
import Cookies from "js-cookie";

export default function Layout({ children, title }) {
  const { state, dispatch } = useContext(Store);
  console.log(state);
  const [cartItemsCount, setCartItemsCount] = useState(0);

  const { data: session, status } = useSession();

  useEffect(() => {
    setCartItemsCount(
      state.cart.cartItems.reduce((total, item) => total + item.cartQty, 0)
    );
  }, [state.cart.cartItems]);

  const logoutHandler = () => {
    Cookies.remove("cart");
    dispatch({ type: "CART_RESET" });
    signOut({ callbackUrl: "/" });
  };

  return (
    <>
      <Head>
        <title>{title ? title + " - " + "Mimart" : "Mimart"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="top-center" limit={1} />

      <div className="flex flex-col min-h-screen justify-between font-karla">
        <header>
          <nav className="h-12 shadow-lg flex items-center justify-between px-4">
            <Link href="/" className="font-bold text-xl ">
              Mimart
            </Link>
            <div className="flex">
              <Link href="/cart" className="p-2">
                Cart
                {cartItemsCount > 0 && (
                  <span className="bg-red-500 text-white text-xs font-bold rounded-full px-2 py-1 ml-2">
                    {cartItemsCount}
                  </span>
                )}
              </Link>

              {status === "loading" ? (
                "loading"
              ) : session?.user ? (
                <Menu as="div" className="inline-block relative p-2">
                  <Menu.Button className="text-blue-500">
                    {session.user.name}
                  </Menu.Button>
                  <Menu.Items className="absolute w-56 right-0 bg-white origin-top-right shadow-lg">
                    <Menu.Item>
                      <DropdownLink href="/profile" className="dropdown-link">
                        Profile
                      </DropdownLink>
                    </Menu.Item>
                    <Menu.Item>
                      <DropdownLink href="/order-history" className="dropdown-link">
                        Order History
                      </DropdownLink>
                    </Menu.Item>
                    {session.user.isAdmin && (
                      <Menu.Item>
                        <DropdownLink
                          href="/admin/dashboard"
                          className="dropdown-link"
                        >
                          Admin Dashboard
                        </DropdownLink>
                      </Menu.Item>
                    )}
                    <Menu.Item>
                      <a
                        href="#"
                        className="dropdown-link"
                        onClick={logoutHandler}
                      >
                        Log out
                      </a>
                    </Menu.Item>
                  </Menu.Items>
                </Menu>
              ) : (
                <Link href="/login" className="p-2">
                  Login
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main className="container m-auto px-4 mt-4">{children}</main>
        <footer className="flex items-center justify-center h-10 shadow-inner text-sm font-semibold">
          Copyright© 2022 Mimart
        </footer>
      </div>
    </>
  );
}
