import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>nextjs ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-600 text-3xl">Welcome helloooo</h1>
    </>
  );
}
